name: build

on:
  push:
    branches: bh/ci
  pull_request:
    branches: bh/ci

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, ghc: ghc884 }
          - { os: ubuntu-latest, ghc: ghc8104 }
          - { os: macos-latest, ghc: ghc8104 }

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
          name: amazonka
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix-build -A ci.library --argstr ghcVersion ${{ matrix.ghc }}
